apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      port: "12000"
      endpoint: /example
      method: POST

    github:
      port: "12000"
      endpoint: /github
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: polling-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-webhook-sa
  dependencies:
    - name: poll-github
      eventSourceName: webhook
      eventName: github
  triggers:
    - template:
        name: kinspect-ci
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-kinspekt-api-
              spec:
                workflowTemplateRef:
                  name: ci
                arguments:
                  parameters:
                  - name: repo-url
                    value: "https://github.com/vmyronovych/kinspect-api"
                  - name: branch
                    value: "main"
                  - name: image
                    value: "vmyronovych/kinspect-api"
                  - name: dockerfile
                    value: "Dockerfile"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci
  namespace: argo-events
spec:
  entrypoint: main
  serviceAccountName: default
  arguments:
    parameters:
    - name: repo-url
      value: "https://github.com/vmyronovych/kinspect-api"
    - name: revision
      value: "main"
    - name: image
      value: "vmyronovych/kinspect-api"
    - name: dockerfile
      value: "Dockerfile"
    - name: deployment-repo-url
      value: "vmyronovych/kinspect-deploy"
    - name: deployment-repo-revision
      value: "main"

  volumeClaimTemplates:
  - metadata:
      name: ci-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi

  volumes:
  - name: docker-config
    secret:
      secretName: docker-registry-creds
      items:
        - key: .dockerconfigjson
          path: config.json

  templates:
  - name: main
    inputs:
      parameters:
      - name: repo-url
      - name: revision
      - name: image
      - name: dockerfile
      - name: deployment-repo-url
      - name: deployment-repo-revision
    steps:
    - - name: clone
        template: clone
        arguments:
          parameters:
          - name: repo-url
            value: "{{inputs.parameters.repo-url}}"
          - name: revision
            value: "{{inputs.parameters.revision}}"

    - - name: debug
        template: ls-debug
        arguments:
          parameters:
          - name: dir
            value: "/mnt/sources"
      
    - - name: docker
        template: docker
        arguments:
          parameters:
          - name: commit-sha
            value: "{{steps.clone.outputs.parameters.commit-sha}}"
          - name: image
            value: "{{inputs.parameters.image}}"
          - name: dockerfile
            value: "{{inputs.parameters.dockerfile}}"

    - - name: deploy-dev
        template: deploy-dev
        arguments:
          parameters:
          - name: repo-url
            value: "{{inputs.parameters.deployment-repo-url}}"
          - name: repo-revision
            value: "{{inputs.parameters.deployment-repo-revision}}"
          - name: new-tag
            value: "{{steps.clone.outputs.parameters.commit-sha}}"

  # Clone task
  - name: clone
    inputs:
      parameters:
      - name: repo-url
      - name: revision # can be tag as well
      artifacts:
      - name: sources
        git:
          repo: "{{inputs.parameters.repo-url}}"
          revision: "{{inputs.parameters.revision}}"
        path: /mnt/sources
    script:
      image: golang:1.19.4
      command: [sh]
      source: |
        #!/bin/sh
        COMMIT_SHA=$(git rev-parse --short HEAD)
        echo $COMMIT_SHA > ../commit-sha.txt
      workingDir: /mnt/sources/
      volumeMounts:
      - name: ci-storage
        mountPath: /mnt/
    outputs:
      parameters:
      - name: commit-sha
        valueFrom:
          path: /mnt/commit-sha.txt

  # Image build and publish task using Kaniko
  - name: docker
    inputs:
      parameters:
      - name: commit-sha
      - name: image
      - name: dockerfile
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: ["/kaniko/executor"]
      args:
      - --dockerfile=/mnt/sources/{{inputs.parameters.dockerfile}}
      - --context=/mnt/sources
      - --destination={{inputs.parameters.image}}:{{inputs.parameters.commit-sha}}
      - --force
      volumeMounts:
      - name: ci-storage
        mountPath: /mnt
      - name: docker-config
        mountPath: /kaniko/.docker
      env:
      - name: DOCKER_CONFIG
        value: /kaniko/.docker

  # Update main branch of deployment repo with new dockerimage tag
  - name: deploy-dev
    inputs:
      parameters:
        - name: repo-url
        - name: repo-revision
        - name: new-tag
    script:
      image: alpine/git:latest
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-token-secret
            key: token
      command: ["/bin/sh"]
      source: |
        REPO_URL=https://$GITHUB_TOKEN@github.com/{{inputs.parameters.repo-url}}
        echo clonning repository $REPO_URL. Revision: {{inputs.parameters.repo-revision}}
        mkdir ./src
        cd ./src
        git clone -b {{inputs.parameters.repo-revision}} $REPO_URL .

        echo clonned files
        ls

        echo updating image tag to {{inputs.parameters.new-tag}}
        sed -i "s|image: vmyronovych/kinspect-api:.*|image: vmyronovych/kinspect-api:{{inputs.parameters.new-tag}}|" src/deployment.yaml

        echo updated tag
        cat src/deployment.yaml | grep image

        echo configure git
        git config --global user.email "viktor.myronovych@gmail.com"
        git config --global user.name "Viktor Myronovych"

        git status
        
        echo stage changes
        git add src/deployment.yaml

        git diff --cached

        echo commit staged changes
        git commit -m "Set image.tag to {{inputs.parameters.new-tag}} in src/deployment.yaml"

        echo push changes
        git push

  - name: ls-debug
    inputs:
      parameters:
      - name: dir
    container:
      image: busybox
      command: [sh, -c]
      args: ["ls -al {{inputs.parameters.dir}}"]
      volumeMounts:
        - name: ci-storage
          mountPath: /mnt/

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-polling-job
  namespace: argo-events
spec:
  schedule: "* * * * *"  # Poll every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: poller
            image: schoolofdevops/github-poller:latest
            env:
            - name: GITHUB_API_URL
              value: "https://api.github.com/repos/vmyronovych/kinspect-api/commits"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token-secret
                  key: token
            - name: LAST_COMMIT_FILE
              value: "/data/last_commit.txt"
            - name: ARGO_EVENT_SOURCE_URL
              value: "http://webhook-eventsource-svc.argo-events.svc.cluster.local:12000/github"
            volumeMounts:
            - name: commit-storage
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: commit-storage
            persistentVolumeClaim:
              claimName: poller-pvc  # Use a PVC to persist the last commit file
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poller-pvc
  namespace: argo-events
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi