apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kinspect-api
  labels:
    app: kinspect-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kinspect-api
  template:
    metadata:
      labels:
        app: kinspect-api
    spec:
      containers:
        - name: kinspect-api
          image: vmyronovych/kinspect-api:71b96ef
          ports:
            - containerPort: 8080  # http-app port
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 30s
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: kinspect-api
            routes:
              - primary: 100
                canary: 0
