apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kinspect-api
spec:
  host: kinspect-api # Your Kubernetes service name
  subsets:
    - name: stable
      labels:
        app: kinspect-api
    - name: canary
      labels:
        app: kinspect-api
