apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kinspect-api
spec:
  endpoints:
  - path: /stats/prometheus
    targetPort: http-envoy-prom
    interval: 15s
  namespaceSelector:
    matchNames:
    - kinspect-dev
  selector:
    matchLabels:
      app.kubernetes.io/instance: kinspect-dev
